steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn -X -P test install -Dusername=kurtkanaskie+cicd@googl.com -Dpassword=$$PASSWORD -Ddeployment.suffix= -Dapigee.config.options=update -Dapigee.config.dir=target/resources/edge -Dapigee.config.exportDir=target/test/integration -Dapi.testtag=@health']
  dir: 'pingstatus-v1'
  secretEnv: ['PASSWORD']

secrets:
- kmsKeyName: projects/apigee-pingstatus-v1/locations/global/keyRings/apigee-cicd/cryptoKeys/password
  secretEnv:
    PASSWORD: CiQAOhJCghpkK6gcVxfJ2xOUHy5Khgg2YCO7k7RT//0Tdpby3oMSMwCyibiLtKztkmx0SdShZTfMYpg45CDEn6lOL+BOAHQ8f7y6U+DedmLTky6BFNKtOZq5IA==