steps: 
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn -P $_PROFILE -Dapigee.username=$$USERNAME -Dapigee.password=$$PASSWORD -Dapigee.org=$_ORG -Dapigee.env=$_ENV install -Dapi.northbound.domain=$_NORTHBOUNDDOMAIN -Ddeployment.suffix=$_DEPLOYSUFFIX -Dapigee.config.options=$_CONFIGOPTIONS -Dapigee.config.dir=target/resources/edge -Dapigee.config.exportDir=target/test/integration -Dapi.testtag=@health -Dcommit="${COMMIT_SHA} via GCP" -Dbranch=${BRANCH_NAME}']
  dir: '.'
  secretEnv: ['USERNAME','PASSWORD']

substitutions:
  _ORG: amer-demo13
  _ENV: prod
  _PROFILE: cicd-prod
  _NORTHBOUNDDOMAIN: amer-demo13-prod.apigee.net
  _CONFIGOPTIONS: update
  _DEPLOYSUFFIX:
options:
  substitution_option: 'ALLOW_LOOSE'

secrets:
- kmsKeyName: projects/apigee-pingstatus-v1/locations/global/keyRings/apigee-cicd-creds/cryptoKeys/cicd-prod
  secretEnv:
    USERNAME: CiQAI9l/6RdvK0HMHvoK+i7nLDEM6l+zBuNDwhdCU3uornHeIGUSSwBr830H+mTPI2JzzWPRP6y6RyXDHnSu4KtgwZXSkDTj0wK6IsCt3t2lLg0dNzD1pG5mW7jlSWUeaucTUKFdmk30xfo1s0XFyuG3hA==
    PASSWORD: CiQAI9l/6YIwCv0cqxgA5LziUupKyBKihwWDF3yRwydLjhmKoA8SNABr830Hz1G2mL6b27brGZBwpIZucm5lomQaHvfYH8c50EegwIiN+NA67sKWvZcZPOM5Xbg=
